#!/usr/bin/env bash

bspc config focus_follows_pointer true

laptop_monitor=$(xrandr --query | grep 'eDP')
left_monitor=$(xrandr --query | grep 'DisplayPort-0')
right_monitor=$(xrandr --query | grep 'HDMI-A-0')

bspc monitor HDMI-A-0 -d "discord" 5 6
bspc monitor DisplayPort-0 -d 1 2 3

bspc rule -a Discord desktop=discord state=fullscreen
